// <auto-generated />
using System;
using BuzzBotTwo.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuzzBotTwo.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20210217230036_BuzzBotTwoInit")]
    partial class BuzzBotTwoInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("BuzzBotTwo.Domain.BotRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Owner"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            Title = "User"
                        });
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventorySlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .HasColumnType("TEXT");

                    b.Property<int>("QualityValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Subclass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.Raid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RaidLockoutId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaidLockoutId");

                    b.ToTable("Raids");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.RaidItem", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAwarded")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaidId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RaidId");

                    b.ToTable("RaidItems");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.RaidLockout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RaidLockouts");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.RaidParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RaidId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ServerUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaidId");

                    b.HasIndex("ServerUserId");

                    b.ToTable("RaidParticipants");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.ReservedItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("ReservedItems");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.SoftResEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Faction")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instance")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RaidDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SoftResEvents");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.SoftResUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Spec")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("SoftResUsers");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Server", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RaidChannel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.ServerBotRole", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerBotRoles");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.ServerUser", b =>
                {
                    b.Property<Guid>("ServerUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ServerBotRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ServerBotRoleId");

                    b.HasIndex("ServerId");

                    b.HasIndex("UserId");

                    b.ToTable("ServerUsers");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.Raid", b =>
                {
                    b.HasOne("BuzzBotTwo.Domain.Entities.RaidLockout", null)
                        .WithMany("Raids")
                        .HasForeignKey("RaidLockoutId");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.RaidItem", b =>
                {
                    b.HasOne("BuzzBotTwo.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuzzBotTwo.Domain.Entities.RaidParticipant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuzzBotTwo.Domain.Entities.Raid", "Raid")
                        .WithMany("Items")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.RaidParticipant", b =>
                {
                    b.HasOne("BuzzBotTwo.Domain.Entities.Raid", null)
                        .WithMany("Participants")
                        .HasForeignKey("RaidId");

                    b.HasOne("BuzzBotTwo.Domain.ServerUser", "ServerUser")
                        .WithMany()
                        .HasForeignKey("ServerUserId");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.ReservedItem", b =>
                {
                    b.HasOne("BuzzBotTwo.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuzzBotTwo.Domain.Entities.SoftResUser", "User")
                        .WithMany("ReservedItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.Entities.SoftResUser", b =>
                {
                    b.HasOne("BuzzBotTwo.Domain.Entities.SoftResEvent", "Event")
                        .WithMany("Users")
                        .HasForeignKey("EventId");

                    b.HasOne("BuzzBotTwo.Domain.Entities.RaidParticipant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId");
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.ServerBotRole", b =>
                {
                    b.HasOne("BuzzBotTwo.Domain.BotRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuzzBotTwo.Domain.Server", "Server")
                        .WithMany("ServerBotRoles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuzzBotTwo.Domain.ServerUser", b =>
                {
                    b.HasOne("BuzzBotTwo.Domain.BotRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuzzBotTwo.Domain.ServerBotRole", null)
                        .WithMany("Users")
                        .HasForeignKey("ServerBotRoleId");

                    b.HasOne("BuzzBotTwo.Domain.Server", "Server")
                        .WithMany("ServerUsers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuzzBotTwo.Domain.Entities.User", "User")
                        .WithMany("ServerUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
